module.exports = {
  audio: require('./audio'),
  clipboard: require('./clipboard'),
  commands: require('./commands'),
  dirwatch: require('./dirwatch'),
  exec: require('./exec'),
  filewatch: require('./filewatch'),
  gpt: require('./gpt'),
  keys: require('./keys'),
  midi: require('./midi'),
  mouse: require('./mouse'),
  notify: require('./notify'),
  obs: require('./obs'),
  reaper: require('./reaper'),
  tabs: require('./tabs'),
  tts: require('./tts'),
  vad: require('./vad'),
  windows: require('./windows'),
};
